// frontend_angular/src/app/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../services/api.service';
import { ToastrService } from 'ngx-toastr';
import { Router } from '@angular/router';
@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
  fullname:string="bakasur"
  name:any
  id:any
  detail:any
  constructor(private apiService:ApiService,private toastr:ToastrService,private router:Router) { }
  loggedinUser:any
  userDetail: any = {
    firstname: '',
    lastname: '',
    address:{ add_line1: '', add_line2: '', city: '', state: '' },
    email: '',
    number: 0,
  };
  ngOnInit(): void {  
    this.loggedinUser = JSON.parse(localStorage.getItem('user') as any);
    this.userDetail=JSON.parse(localStorage.getItem('user') as any);
    this.id=this.userDetail._id
   
  }

displayStyle = "none";
  
  openPopup() {
    this.displayStyle = "block";
  }

  closePopup() {
    this.displayStyle = "none";
  }

  customerEdit(data:any )
  {
    this.apiService.edit(this.id,data).subscribe((res:any) => {
      console.log(res);
      if(res.status){
        this.closePopup() 

        localStorage.setItem('user', JSON.stringify(res.result));
        this.ngOnInit()
      }
    });
  }

  handleLogout() {
    localStorage.clear();
    this.toastr.success('Logout Successfull','Success')
    this.router.navigate(['/login']);
  }
}
<!-- <button type="button" class="btn btn-danger" (click)="getName()">getName</button> -->
<div align="right">
<button  type="button" class="btn btn-primary" (click)="openPopup()">
  Update Profile
</button>
&nbsp;
  <button class="btn btn-danger" (click)="handleLogout()">Logout</button>
</div>
<p>welcome {{ loggedinUser.firstname + " " + loggedinUser.lastname
}}</p>
<div class="modal" tabindex="-1" role="dialog" [ngStyle]="{'display':displayStyle}">
  <form #editForm="ngForm" >
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Edit Form</h4>
        </div>
        <div class="modal-body">

          <div class="row">
            <div class="col-md-6 mb-4">
              <input  name="firstname" required #firstname="ngModel" [minlength]="3" pattern='[a-zA-Z ]*' [(ngModel)]="userDetail.firstname" class="form-control">
              <label class="form-label" for="firstName">First Name</label><br/>
              <span *ngIf="firstname.invalid && firstname.touched">firstname required</span>
              <div *ngIf="firstname.errors?.['pattern']">First name contains only letters</div>

             </div>
             <div class="col-md-6 mb-4">
               <input  name="lastname" required #lastname="ngModel" pattern='[a-zA-Z ]*' [(ngModel)]="userDetail.lastname" class="form-control">
               <label class="form-label" for="lastName">Last Name</label><br/>
               <span *ngIf="lastname.invalid && lastname.touched">Lastname required</span>
               <div *ngIf="lastname.errors?.['pattern']">Last name contains only letters</div>

             </div>
           </div>

           <div class="row">
            <div class="col-md-6 mb-4"> 
          <input  name="add_line1" required #address1="ngModel" [(ngModel)]="userDetail.address.add_line1"  class="form-control">
          <label class="form-label" for="address1">Address1</label><br/>
          <span *ngIf="address1.invalid && address1.touched">Add_line1 required</span>

        </div>
        <div class="col-md-6 mb-4">
          <input  name="state" required #state="ngModel" [(ngModel)]="userDetail.address.state" class="form-control">
          <label class="form-label" for="state">State</label><br/>
          <span *ngIf="state.invalid && state.touched">state required</span>
          
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 mb-4"> 
          <input  name="city" required #city="ngModel" [(ngModel)]="userDetail.address.city" class="form-control">
          <label class="form-label" for="city">City</label><br/>
          <span *ngIf="city.invalid && city.touched">city required</span>

        </div>
        <div class="col-md-6 mb-4">
          <input  name="number" [(ngModel)]="userDetail.number" required #number="ngModel" pattern='[0-9]*$' [minlength]="10" [maxlength]="10"class="form-control">
          <label class="form-label" for="number">Number</label><br/>
          <span *ngIf="number.invalid && number.touched">number required</span>
          <div *ngIf="number.errors?.['pattern']">Number contains only digit</div>
          <div *ngIf="number.errors?.['minlength'] ">Number contains 10 only digit</div>

        </div>
      </div>
      <input  name="email" [(ngModel)]="userDetail.email" required #email="ngModel" pattern="^[a-zA-Z0-9]+(?:\.[a-zA-Z0-9]+)*@[a-zA-Z0-9]+(?:\.[a-zA-Z0-9]+)*$" class="form-control" readonly>
      <label class="form-label" for="email">Email</label>
      <span *ngIf="email.invalid && email.touched">email required</span>
          <div *ngIf="number.errors?.['pattern']">Invalid email</div>
          
        </div>
        <div class="modal-footer">
         
          <button class="btn btn-success" (click)="customerEdit(editForm.value)" [disabled]='!editForm.valid'>Update</button>
          <button type="button" class="btn btn-danger" (click)="closePopup()">
            Close
          </button>
         
        </div>
      </div>
    </div>
  </form> 

</div>

// frontend_react/src/Components/Dashboard.js
import React from 'react'
import { useEffect,useState } from 'react'
import { Navigate, useNavigate } from 'react-router-dom'
import { Modal, ModalHeader } from "reactstrap"
import { formnewUpdate } from '../Services/auth.service'
export default function Dashboard() {
    const [show, setShow] = useState({})
    const [modal, setmodal] = useState(false)
    const navigate=useNavigate()
    useEffect(() => {
        // setShow(localStorage.getItem("user"))
        setShow(JSON.parse(localStorage.getItem('user') ))
    }, [])

    // const [input,setInput]=useState({
    //     firstname:" ",
    //     lastname:" ",
    //     add_line1:" ",
    //     add_line2:" ",
    //     state:" ",
    //     city:" ",
    //     number:" ",
    //     email:" ",
    //     password:" "
    //   })
     
    const user = JSON.parse(localStorage.getItem("user"));
  const initial = {
    _id: user._id,
    firstname: user.firstname,
    lastname: user.lastname,
    add_line1: user.address.add_line1,
    add_line2: user.address.add_line2,
    state: user.address.state,
    city: user.address.city,
    number: user.number,
    email: user.email,
  };
      console.log(initial);
      const updateuser = async (e) =>{
        e.preventDefault();
        const apiResponse=await formnewUpdate(show,show._id)
        console.log(apiResponse.data.result)
        if(apiResponse.data.status){
            localStorage.setItem("user",JSON.stringify(apiResponse.data.result))
            setmodal(false)
        }
      }
    
      const inputHandler= (e)=>{

        const {name,value}=e.target

        setShow((preValue)=>({
          ...preValue,
          [name]:value
        }))
      }

      const logout= ()=>{
        localStorage.clear()
        navigate("/login")
      }
      const closePopup = ()=>{
        console.log("inside popclose");
        setShow(JSON.parse(localStorage.getItem('user') ))

        setmodal(false)
      }
  return (
    <>
    <h1>welcome {show.firstname} {show.lastname}</h1>
         <Modal
                size=""
                isOpen={modal}
                toggle={() =>closePopup() }
            >
                <ModalHeader
                
                     //toggle={() => setmodal(!modal)}
                     toggle={() =>closePopup() }
                >

                    </ModalHeader>
                    <div>
                        <form type="submit" >

                        <div class="row form-group">
                         <div class="col-md-6 mb-4 form-group">
                                <div class="form-outline form-group">
                                    <input type="text" className="form-control form-control-lg" value={show.firstname} name="firstname" onChange={(e)=>inputHandler(e)}/>
                                    <label class="form-label" for="firstname">First Name</label>
                                </div>
                        </div>
                        <div class="col-md-6 mb-4">
                                <div class="form-outline">
                                    <input type="text" name="lastname" className="form-control form-control-lg" value={show.lastname} onChange={(e)=>inputHandler(e)} />
                                    <label class="form-label" >lastname</label>
                                </div>
                        </div>
                        </div>

                        <div class="row">
                         <div class="col-md-6 mb-4">
                                <div class="form-outline">
                                    <input type="text" name="add_line1" class="form-control form-control-lg" value={show.address.add_line1}  onChange={(e)=>inputHandler(e)} />
                                    <label class="form-label" for="add_line1">add_line1</label>
                                </div>
                        </div>
                        <div class="col-md-6 mb-4">
                                <div class="form-outline">
                                    <input type="text" id="add_line2" name="add_line2" class="form-control form-control-lg" value={show.address.add_line2}   onChange={(e)=>inputHandler(e)} />
                                    <label class="form-label" >add_line2</label>
                                </div>
                        </div>
                        </div>

                        <div class="row">
                         <div class="col-md-6 mb-4">
                                <div class="form-outline">
                                    <input type="text" name="state" class="form-control form-control-lg" value={initial.state} onChange={(e)=>inputHandler(e)} />
                                    <label class="form-label" for="state">state</label>
                                </div>
                        </div>
                        <div class="col-md-6 mb-4">
                                <div class="form-outline">
                                    <input type="text" name="city" class="form-control form-control-lg" value={initial.city}   onChange={(e)=>inputHandler(e)} />
                                    <label class="form-label" >city</label>
                                </div>
                        </div>
                        </div>

                        <div class="row">
                         <div class="col-md-6 mb-4">
                                <div class="form-outline">
                                    <input type="text" name="number" class="form-control form-control-lg" value={show.number} onChange={(e)=>inputHandler(e)} />
                                    <label class="form-label" for="mobile">mobile</label>
                                </div>
                        </div>
                        <div class="col-md-6 mb-4">
                                <div class="form-outline">
                                    <input type="text" name="email" class="form-control form-control-lg" value={show.email}  onChange={(e)=>inputHandler(e)} readOnly/>
                                    <label class="form-label" >email</label>
                                </div>
                        </div>
                        </div>


                        {/* <div class="row">
                         <div class="col-md-6 mb-4">
                                <div class="form-outline">
                                    <input type="text" name="passwaord" class="form-control form-control-lg" onChange={(e)=>inputHandler(e)}  />
                                    <label class="form-label" for="passwaord">Passwaord</label>
                                </div>
                        </div>

                        </div> */}


                           
                        <div class="row">
                         <div class="col-md-6 mb-4">
                            <button type="submit" class="btn btn-outline-success btn-rounded" onClick={updateuser}>Update</button>
                        </div>
                        <div class="col-md-6 mb-4">
                        </div>
                        </div>

                        </form>
                    </div>
               
            </Modal>
            <div align="right">
            <button class="btn btn-outline-success btn-rounded" data-mdb-ripple-color="dark" onClick={() => setmodal(true)}>
                Update Profile
            </button>

            <button class="btn btn-outline-danger btn-rounded" data-mdb-ripple-color="dark" onClick={() => logout()}>
                Logout
            </button>
            </div>
    </>
  )
}
