// frontend_angular/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../services/api.service';
import { Router } from '@angular/router';
import { FormBuilder, FormControl, FormGroup, Validators } from '@angular/forms';
import { ToastrService } from 'ngx-toastr';
@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  loginForm:any
  
    constructor(private apiService:ApiService,private router:Router,
    private toastr: ToastrService,
    ) { }

  ngOnInit(): void {

    this.loginForm=new FormGroup({
      
      'email': new FormControl("",[Validators.required,  	Validators.pattern("^[a-zA-Z0-9]+(?:\.[a-zA-Z0-9]+)*@[a-zA-Z0-9]+(?:\.[a-zA-Z0-9]+)*$"),
    ]),
      'password': new FormControl("",[Validators.required,Validators.minLength(8)]),
    })
  }

  // userLogin(item:any )
  // {
  //   console.log(item.value);
    
  //   this.apiService.login(item.value).subscribe((res:any) => {
  //     console.log(res);
  //     localStorage.setItem("Token",res.token)
  //     localStorage.setItem("id",res.id)
  //     if(res.token){
  //     this.router.navigate(["dashboard"])

  //     }
  //   });
  // }
  userLogin(){
    this.apiService.login(this.loginForm.value).subscribe((res:any) => {
      console.log(res);
      if(res.status==200){
        this.toastr.success(res.message, 'Success');
        localStorage.setItem('token', res.token);
        localStorage.setItem('user', JSON.stringify(res.result));
        this.router.navigate(["dashboard"])
        }
    });
  }

}

<!-- <p>login works!</p>
<form #loginForm='ngForm' (ngSubmit)=userLogin(loginForm.control)>
    <div class="col-md-6">
    <div class="form-group " >
      <label for="exampleInputEmail1">Email address</label>
      <input type="email" class="form-control" id="exampleInputEmail1" name="email" aria-describedby="emailHelp" placeholder="Enter email" ngModel>
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" id="exampleInputPassword1" name="password" placeholder="Password" ngModel>
    </div>
    </div>


   

    <button  class="btn btn-primary">Submit</button>
  </form> -->

  <section class="vh-100 bg-image"
  style="background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-12 col-md-9 col-lg-7 col-xl-6">
          <div class="card" style="border-radius: 15px;">
            <div class="card-body p-5">
              <h2 class="text-uppercase text-center mb-5">Login</h2>

              <form [formGroup]="loginForm">

                

                <div class="form-outline mb-4">
                  <input type="email" id="form3Example3cg" class="form-control form-control-lg" formControlName="email"/>
                  <label class="form-label" for="form3Example3cg">Your Email</label><br/>
                  <span *ngIf="loginForm.get('email').hasError('required') && loginForm.get('email').touched ">
                    Email is required *
                    </span>
                    <span *ngIf=" loginForm.get('email').hasError('pattern')">
                    Invalid Email Pattern
                    </span>
                </div>
                

                <div class="form-outline mb-4">
                  <input type="password" id="form3Example4cg" class="form-control form-control-lg" formControlName="password"/>
                  <label class="form-label" for="form3Example4cg">Password</label><br/>
                  <div *ngIf="loginForm.get('password').hasError('required') && loginForm.get('password').touched ">
                    password is required *
                    </div>
                    <div *ngIf=" loginForm.get('password').hasError('pattern')">
                    Invalid password Pattern
                    </div>
                </div>

                

                <div class="d-flex justify-content-center">
                  <button type="button" (click)="userLogin()" 
                    class="btn btn-success btn-block btn-lg gradient-custom-4 text-body">Login</button>
                </div>

               
                

              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

// frontend_react/src/Components/Login.jsx
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import { loginCustomer } from "../Services/auth.service";
import { Link } from "react-router-dom";
function Login() {

 const  navigate = useNavigate()
  const [input,setInput]=useState({
    email:" ",
    password:" "
  })
 
  
  const loginuser = async (e) =>{
    e.preventDefault();
    const apiResponse=await loginCustomer(input.email,input.password)
    console.log(apiResponse.data);
    if(apiResponse.data.status){
      navigate("/Popup")
      localStorage.setItem("user",JSON.stringify(apiResponse.data.result))
      localStorage.setItem("token",JSON.stringify(apiResponse.data.token))

    }
  }

  const inputHandler= (e)=>{
    const {name,value}=e.target
    setInput((preValue)=>({
      ...preValue,
      [name]:value
    }))
    //console.log(input)
  }

  return(
    <>
    <div className="container">
      <div className="row">
        <div className="col-md-4">
    <form>
    <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email"
    onChange={(e)=>inputHandler(e)}/>
   
  </div>
    
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input
    name="password" 
    
    class="form-control" 
    id="exampleInputPassword1" 
    placeholder="Password" onChange={(e)=>inputHandler(e)}/>
  </div>

  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1"/>
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  

  <button type="submit" class="btn btn-primary" onClick={loginuser}>Submit</button>
  <h3>
  <Link class="nav-link" to="/form">New User</Link>

        </h3>
 
</form>
</div>
</div>
</div>
    </>
  )
  
  }

  export default Login
